### ISSUE TITLE
By default, an extra upvote is counted

### ISSUE THREAD

**Issue by NathanielIR** [Memmy-App/memmy#451] opened 2023-07-07 17:26 UTC
Every time I post on Lemmy, before anyone upvotes, the Memmy app shows 2 upvotes. My own default upvote as well as an extra one for some reason. I can verify that this is not an actual upvote since every other app and site shows the correct number. As far as I can tell, this single extra upvote just sort of stays there for all posts

**Comment by sgriff96** [comment] 2023-07-07 17:48
Dupe of #252

**Closed by sgriff96** 2023-07-07 17:48 UTC
Labels: bug
