### ISSUE TITLE
Embedded Video

### ISSUE THREAD

**Issue by Voltaia** [Memmy-App/memmy#1001] opened 2023-08-20 14:33 UTC
### Check for open issues

- [X] I have verified that another issue for this is not open, or it has been closed and has not been properly implemented.

### What is the feature that you would like to have added?

When a user posts a video link, there should be an embedded video in the post.

### Solution

When a user is scrolling through Memmy, they should be able to find and watch video among the rest of the media.

### Alternatives

Seeing as we can not exactly host video, I think this is the alternative solution.

**Comment by eoddc5** [comment] 2023-08-20 15:22
Duplicate of #399

**Closed by eoddc5** 2023-08-20 15:22 UTC
Labels: enhancement, triage
