### ISSUE TITLE
Community population and post count show in search results.

### ISSUE THREAD

**Issue by hugpeter** [Memmy-App/memmy#435] opened 2023-07-06 22:05 UTC
When searching for communities in the search tab, "nba" for example, there are several results with nba, but no additional data for subscriber count, etc. this forces the user to click into each community just to compare them with each other. Additionally the resulting search options should display with highest subscription count to the top. The highest sub count nba community currently shows at the very end of the list.

**Comment by eoddc5** [comment] 2023-07-12 17:49
closing: duplicate of #338

**Closed by eoddc5** 2023-07-12 17:49 UTC
Labels: enhancement, low priority, visual
