### ISSUE TITLE
Report Post Option Misbehaves

### ISSUE THREAD

**Issue by ainen** [Memmy-App/memmy#577] opened 2023-07-11 00:24 UTC
**Describe the bug**
When opening the “Report Post” view, it looks different than the “Block Community” view. The only way to exit the “Report Post” view is to tap cancel, tapping anywhere else does nothing. 

**To Reproduce**
1. Go to a post
2. Tap the three dot icon
3. Attempt to exit by tapping anywhere except the “Cancel” button. 

**Expected behavior**
Tapping anywhere should close the “Report Post” button instead of just the “Cancel” button. 

**Screenshots**
![image](https://github.com/Memmy-App/memmy/assets/1300058/57d7993c-d7f6-4c7e-9aac-e25b4642ae48)
![image](https://github.com/Memmy-App/memmy/assets/1300058/d8bf870d-fb21-4e02-afc0-3eed7cb9f5f8)

**Smartphone (please complete the following information):**
 - Device: iPhone 14 Pro
 - OS: iOS 17 Beta 3
 - Version 0.1.0 (14)

**Comment by ainen** [comment] 2023-07-11 00:25
For some reason, I am unable to take a screenshot of the “Report Post” option.

**Comment by eoddc5** [comment] 2023-07-11 10:10
@gkasdorf this is similar to my other [Bug issue](https://github.com/Memmy-App/memmy/issues/511) 

But it’s generally the same thing. Menus are not facing the same look and behavior

**Comment by eoddc5** [comment] 2023-07-11 10:10
Closing as a duplicate of 511

**Comment by eoddc5** [comment] 2023-07-11 19:53
@Felix-Staud since you linked a PR to this, I am going to close #511 , so we only have one active issue open for the same bug

can you please ensure that the scope of this PR includes other items from #511 

`In a post, if you click the … menu button, there’s no haptics

You can’t close the menu pop up by clicking outside the bounds. Only by hitting cancel

Closing the menu doesn’t produce haptics

At the same time, the comments … menu in a post WILL produce haptics on click. You can escape the menu by clicking on the sceen outside of it OR hitting the cancel button. And there’s a haptic feedback on close.

Would be great to reproduce the same behavior on the post menu that is there on the comments menu (comments menu actions are nicer ux)

The menu's are also different visually (with a space between actions and cancel on comments ... , but no space in post)`

**Closed** 2023-07-11 20:13 UTC
Labels: bug, duplicate, high priority

**Comment by Felix-Staud** [comment] 2023-07-11 20:20
@eoddc5 I'll have to make a new PR as that one was already merged. Here is a tasklist to follow

- [ ] In a post, if you click the … menu button, there’s no haptics

- [ ] You can’t close the menu pop up by clicking outside the bounds. Only by hitting cancel

- [ ] Closing the menu doesn’t produce haptics. At the same time, the comments … menu in a post WILL produce haptics on click. 

- [ ] You can escape the menu by clicking on the sceen outside of it OR hitting the cancel button. And there’s a haptic feedback on close.

- [ ] Would be great to reproduce the same behavior on the post menu that is there on the comments menu (comments menu actions are nicer ux)

- [ ] The menu's are also different visually (with a space between actions and cancel on comments ... , but no space in post)
