### ISSUE TITLE
[Bug]: Match system light/dark theme doesn’t work

### ISSUE THREAD

**Issue by th3dogcow** [Memmy-App/memmy#896] opened 2023-07-30 07:05 UTC
### Check for open issues

- [X] I have verified that another issue for this is not open, or it has been closed and has not been fixed.

### Minimal reproducible example

Enable the setting to match system light/dark setting. Select different themes for light and dark. Dark will always be the chosen one no matter what the system is set to. 

### Expected Behavior

Should switch based on system setting. 

### Version

0.5.0 (13)

### App Store or TestFlight?

TestFlight

### iOS Version

16.x

### Device

iPhone 8

**Comment by gkasdorf** [comment] 2023-07-30 07:38
Hmm. I am not able to reproduce. Are you give it a few seconds to switch? There's an open bug with React Native and I have had to implement a bit of a hack to get around it, so it isn't *instant* but shouldn't take long to switch between the two. Also, just as a test, have you tried restarting the app as well?

**Comment by th3dogcow** [comment] 2023-07-30 12:42
Yeah I have waited for a certain amount of time. 

https://github.com/Memmy-App/memmy/assets/50811949/06f68f21-f419-4777-8d93-77cd1068156b

This is how it appears. Now it’s stuck on light mode. I’ve restarted the app multiple times. This started to happen after the switch was made to the new interface library two updates ago if I remember correctly.

**Comment by th3dogcow** [comment] 2023-07-30 12:48
After restarting my phone and manually switching between light and dark mode in the settings it seems to be functioning correctly. I’ll find out in the morning if it works for the automatic setting. I’ll update tomorrow.

**Comment by th3dogcow** [comment] 2023-07-30 23:56
So I investigated more. If I switch manually in the system settings between light and dark Memmy switches as expected. 

But if my phone switches automatically due to the time of the day, then Memmy does not switch. 

So, when I opened the app this morning, it continued to stay in dark mode. 

Two revisions earlier it functioned correctly. So I’m not sure what’s going on. 

Of course it is not urgent but I think there is still a bug here.

**Comment by gkasdorf** [comment] 2023-07-30 23:58
Interesting. I guess I have not tested with that specifically as it's sort of hard to do...

I'll look into the React Native issue as well and see if it may be related, or it could be something with the hack that I've had to use to prevent the weird bug they have going on. Thanks for letting me know.

**Comment by herrherrmann** [comment] 2023-07-31 10:04
I’ve also had this issue since version 0.5.0 (or maybe one version earlier). Before that, Memmy correctly followed the system theme, but now it’s always in dark mode. I haven’t changed anything regarding the iOS system settings in the meantime.

**Comment by Zuawg** [comment] 2023-07-31 15:40
I’m on the App Store version 0.5.0 and this issue has started happening to me today.

**Comment by gkasdorf** [comment] 2023-08-02 23:01
There's an open bug here as well. https://github.com/facebook/react-native/issues/38753 We will see what they say.

**Comment by jloveridge-tornado** [comment] 2023-08-04 11:37
I also have this issue. The "Match System Light/Dark Theme" toggle is acting as a dark them toggle right now. If it's enabled, the app is in dark theme no matter what. The only way to switch back to light theme is to toggle it off. It was working perfectly in previous versions.

**Comment by SpenHub** [comment] 2023-08-11 00:22
Any updates on this? 🤗

**Comment by schmurnan** [comment] 2023-08-19 12:09
Also have the issue, and have had it for a few weeks. Was on TestFlight, now on App Store version v0.5.1 (1).

**Comment by instamat** [comment] 2023-08-28 06:11
Same issue. Version 0.6.1 (1)

**Comment by hemightbe** [comment] 2023-09-01 14:45
Same issue here on 0.5.1 - I can manually switch themes np, but when selecting automatic it stays Dark

**Comment by elementeight** [comment] 2023-09-22 03:32
Got the same issue here too. 0.5.1

iOS 17.0

Manually switching between light and dark in iOS settings works, but when Dark/Light Mode switches automatically from time of day, the theme remains in the previous state it was in before.

**Comment by gkasdorf** [comment] 2023-10-21 04:55
All theme issues are now fixed. Update coming this week.

**Closed by gkasdorf** 2023-10-21 04:55 UTC
Labels: bug, low priority, in progress, visual
