### ISSUE TITLE
User needs to re-enter password when app is force closed

### ISSUE THREAD

**Issue by alexv93** [Memmy-App/memmy#578] opened 2023-07-11 01:34 UTC
Memmy requires you to sign-in again when you force close the app and open the app again. I've also noticed the behavior when the app has been suspended in iOS and you open it again.

**To Reproduce**
1. Open Memmy and try to post comment.
2. Re-enter credentials in settings account page.
3. Try to post comment.
4. Force close Memmy.
5. Try top post comment again.

**Expected behavior**
Memmy will allow you to post comments without having you sign-in every time you force close the app. An alternative would be to display message to prompt user to enter credentials again.

**Screenshots**
Screen recording of bug:
https://share.icloud.com/photos/0120KM6O9bL46D66i8wvBd3ZA

**Smartphone (please complete the following information):**
 - Device: iPhone 12 Pro
 - OS: iOS 16.5.1(a)
 - Version 16.5.1(a)

**Comment by ktgd** [comment] 2023-07-11 01:36
duplicate of #560

**Comment by ktgd** [comment] 2023-07-11 01:37
Duplicate of #560

**Closed** 2023-07-11 01:38 UTC
Labels: bug
