### ISSUE TITLE
Communities flicker if no posts to show for sort by top

### ISSUE THREAD

**Issue by enghseb** [Memmy-App/memmy#811] opened 2023-07-22 10:16 UTC
### Check for open issues

- [X] I have verified that another issue for this is not open, or it has been closed and has not been fixed.

### Minimal reproducible example

* Reinstall Memmy (might not be necessary)
* login to Lemm.ee (likely does not matter)
* Set default sort to top 6h
* visit community with no posts in the last 6h (Sweden.world as an example)
* 
This behavior was reported earlier without steps to reproduce here (where a video can be seen as well): https://github.com/Memmy-App/memmy/issues/807

### Expected Behavior

The community should show up as empty

### Version

0.5(4)

### App Store or TestFlight?

TestFlight

### iOS Version

16.x

### Device

iPhone 13 Pro

**Comment by eoddc5** [comment] 2023-07-22 13:45
Still works 

Might be a lemm.ee account issue 

Closing because this is a duplicate of #807

**Closed by eoddc5** 2023-07-22 13:45 UTC
Labels: bug, triage

**Comment by enghseb** [comment] 2023-07-22 13:49
> Still works 
> 
> 
> 
> Might be a lemm.ee account issue 
> 
> 
> 
> Closing because this is a duplicate of #807

Definitely not. Same problem on Lemmy.world. I've replicated it three times by uninstalling and following the steps. 

But might be something else on my side I guess!

**Comment by ebits21** [comment] 2023-07-22 16:08
I'm definitely getting this as well. I get it when I search and I open a community that I think doesn't have any posts. Just flickers.

I'll test further. Does not happen for communities with posts for me.
