### ISSUE TITLE
Feature: find in comments

### ISSUE THREAD

**Issue by chowanana99** [Memmy-App/memmy#295] opened 2023-07-01 21:39 UTC
**Is your feature request related to a problem? Please describe.**
I'd like to be able to find comments containing specific words

**Describe the solution you'd like**
Basically a cmd + F for the comments section, with arrows to change between the results (in case there were more than one)

**Comment by RustedSwitch** [comment] 2023-07-02 11:18
I just posted a duplicate of this (I searched for different terms than this request used). Mine is more verbose, which could be better or worse, so I’ll leave mine open and let the team decide which to keep.

**Comment by sgriff96** [comment] 2023-07-07 20:32
Yea will close this in favor of #316

**Closed by sgriff96** 2023-07-07 20:32 UTC
Labels: enhancement
