### ISSUE TITLE
Default sort has misplaced “cancel” and “new”, tapping “cancel” crashes the app

### ISSUE THREAD

**Issue by burakdede0** [Memmy-App/memmy#559] opened 2023-07-10 09:10 UTC
**Describe the bug**
Default sort options have misplaced New and Cancel buttons. Tapping “Cancel” (I wanted to choose new) crashes the app. Tapping “New” cancels the menu.

**To Reproduce**
1. Go to Settings > Content > Default Sort
2. Click on Cancel
3. App crashes

**Expected behavior**
New and cancel should switch places and tapping them shouldn’t crash.

**Screenshots**
![EB0C5449-E8F7-495D-87D4-603B8A2D5E30](https://github.com/Memmy-App/memmy/assets/29973158/b094c8ea-cd15-4034-aa0a-d28311f9bdbe)

**Smartphone (please complete the following information):**
 - Device: iPhone 7
 - OS: 15.7.5
 - Version 0.1.0 (14) TestFlight

**Logs:**
Sent them with Email. I can provide it here if you want.

**Additional context**
Phone is jailbroken, I don’t think this makes difference.

**Comment by bviefhues** [comment] 2023-07-10 10:58
Duplicate of #487

**Closed** 2023-07-11 00:46 UTC
Labels: bug
