### ISSUE TITLE
[Bug]: Tab bar height wrong for iPhones with Touch ID 

### ISSUE THREAD

**Issue by th3dogcow** [Memmy-App/memmy#983] opened 2023-08-12 12:20 UTC
### Check for open issues

- [X] I have verified that another issue for this is not open, or it has been closed and has not been fixed.

### Minimal reproducible example

The tab bar doesn’t adjust for Touch ID models (8, SE2,SE3). 

### Expected Behavior

Not to have extra space at the bottom. 

![IMG_8745](https://github.com/Memmy-App/memmy/assets/50811949/7b0d5600-da7d-4fd1-a698-7bee487578f5)

### Version

0.6.1(1)

### App Store or TestFlight?

TestFlight

### iOS Version

16.x

### Device

iPhone 8

**Comment by eoddc5** [comment] 2023-08-12 13:30
Duplicate of #733

**Closed by eoddc5** 2023-08-12 13:30 UTC
Labels: bug, triage
