### ISSUE TITLE
[Feature]: User-side lists for communities

### ISSUE THREAD

**Issue by aquariusdev** [Memmy-App/memmy#987] opened 2023-08-13 17:41 UTC
### Check for open issues

- [X] I have verified that another issue for this is not open, or it has been closed and has not been properly implemented.

### What is the feature that you would like to have added?

Allow users to create lists for communities. 

This is already useful in the microblogging Fediverse for sorting posts from specific users (or even for hashtags and instances), so it should be useful for the threadiverse. Many communities sharing similar content and themes are splayed across multiple instances, so I’d like to be able to sort them easily as I do with lists and tag groups. 

### Solution

- clicking “Subscribe” triggers appearance of “Lists” button
- Lists button, when clicked, opens menu to “Add/Remove from lists”, with switch buttons on right of list names to add a community to (more than one) list
- “Create New List” button at the bottom of “Add/remove from lists” menu to open up a dialog box for entering a list name
- drop-down menu from top to see lists in “Feed”, akin to Ice Cubes’ drop down menu in Timeline
- Selecting a list shows posts from listed communities 

### Alternatives

N/A

**Comment by sgriff96** [comment] 2023-08-13 18:44
Dupe of #293

**Closed** 2023-08-13 18:44 UTC
Labels: feature request
