### ISSUE TITLE
Mark posts as read on scroll

### ISSUE THREAD

**Issue by pitrisss** [Memmy-App/memmy#711] opened 2023-07-16 17:15 UTC
**Is your feature request related to a problem? Please describe.**
When I scroll on a post that I won't open, or won't vote on, I would like to mark it as read, so it won't show up again.

**Describe the solution you'd like**
A switch which would toggle this functionality on or off.

**Comment by eoddc5** [comment] 2023-07-16 17:18
This is a duplicate of another ticket.

**Closed by eoddc5** 2023-07-16 17:18 UTC
Labels: duplicate, enhancement, wontfix, low priority

**Comment by gkasdorf** [comment] 2023-07-23 02:04
@pitrisss This is complete.
