### ISSUE TITLE
[Bug] subscriber count does not display correct amount

### ISSUE THREAD

**Issue by johtok** [Memmy-App/memmy#997] opened 2023-08-17 12:03 UTC
### Check for open issues

- [X] I have verified that another issue for this is not open, or it has been closed and has not been fixed.

### Minimal reproducible example

Go to community screen, then the subscriber counter over the community name (denoted using a person icon) is wrong.

### Expected Behavior

I would expect the person icon on a community page to denote subscriptions.

### Version

0.5.1.1

### App Store or TestFlight?

App Store

### iOS Version

16.x

### Device

iPhone 12 Pro

**Comment by eoddc5** [comment] 2023-08-17 15:56
Known issue. Duplicate of another ticket

**Closed by eoddc5** 2023-08-17 15:56 UTC
Labels: bug, triage
