### ISSUE TITLE
[Bug]: Links to URLs that contain special characters may be getting cut off

### ISSUE THREAD

**Issue by thiscoldhouse** [Memmy-App/memmy#998] opened 2023-08-17 15:23 UTC
### Check for open issues

- [ ] I have verified that another issue for this is not open, or it has been closed and has not been fixed.

### Minimal reproducible example

I've received a handful of bug reports to my site, and I've narrowed it down to people opening links to the site on the memmy app, so I'm forwarding it along. I don't have a way to test the memmy app, so this isn't the best bug report, but here is a lemmy link to a relevant url:

https://lemmy.ml/post/2978553?scrollToComments=true

Users are reporting getting sent to https://theluddite.org instead of https://theluddite.org/#!post/barbenheimer

I'm not sure this will be a reproducible example, as I cannot test it, but I hope this is helpful.

### Expected Behavior

Should go to https://theluddite.org/#!post/barbenheimer

### Version

N/A

### App Store or TestFlight?

App Store

### iOS Version

17.x Beta

### Device

N/A

**Comment by eoddc5** [comment] 2023-08-17 15:57
This is a duplicate of #989 

please search for the issue before posting a new ticket 

there’s a qualifier in the ticket form that you search for it first and you didn’t do that. ¯\_(ツ)_/¯

**Closed by eoddc5** 2023-08-17 15:57 UTC
Labels: bug, triage

**Comment by thiscoldhouse** [comment] 2023-08-18 03:00
No apostrophe in my link so I looked right past that one. Hope being rude made you feel better. Have a wonderful rest of your week.
