### ISSUE TITLE
Push notifications can’t be enabled

### ISSUE THREAD

**Issue by fmflurry** [Memmy-App/memmy#557] opened 2023-07-10 08:30 UTC
**Describe the bug**
Can’t enable push notifications for my account. It was enabled before the hack, I couldn’t remove push notifications after the attack before deleting and reinstalling the app. When I try to enable the push notifications cogwheel loader spins forever.

**To Reproduce**
1. Go to Profile tab
2. Click on the settings button
3. Go to accounts
4. Go to change account settings
5. Click on slider button to enable push notifications 
6. Info pop-up opens, click continue
7. Cogwheel spins forever

**Expected behavior**
The push notification setting is enabled and cogwheel stop loading.

**Smartphone (please complete the following information):**
 - Device: iPhone 11 Pro
 - OS: iOS 16.5.1
 - Version 0.0.2 (16)

**Comment by OutOfPhase87** [comment] 2023-07-10 15:07
I'm seeing the exact same behavior on the exact same device / versions.

**Comment by fmflurry** [comment] 2023-07-10 15:09
Yep, request on `https://memmy.app/api/push/enable` returns a `503 service unavailable`.

```
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>503 Service Unavailable</title>
</head><body>
<h1>Service Unavailable</h1>
<p>The server is temporarily unable to service your
request due to maintenance downtime or capacity
problems. Please try again later.</p>
</body></html>
```

**Comment by einsteinx2** [comment] 2023-07-10 16:44
I'm also unable to turn off push notifications for the 2 accounts I had them on for, so I guess the `disable` endpoint is also down. I assume the whole push notification service is probably down.

**Comment by einsteinx2** [comment] 2023-07-10 16:45
Also fwiw there is another related UI/UX bug here in that there doesn't seem to be a reasonable timeout for the spinner. It just blocks the UI forever. It should have like a 10 second timeout and then show an error, or possibly it's receiving the 503 error immediately but not handling it, so the app just hangs.

**Comment by fmflurry** [comment] 2023-07-10 17:26
> Also fwiw there is another related UI/UX bug here in that there doesn't seem to be a reasonable timeout for the spinner. It just blocks the UI forever. It should have like a 10 second timeout and then show an error, or possibly it's receiving the 503 error immediately but not handling it, so the app just hangs.


Yes, there is no mechanism to handle http error response nor a reasonable timeout (I waited five minutes and it was still spinning).

**Comment by gkasdorf** [comment] 2023-07-10 19:40
I'm working on this. It is a combination of issues all related to the incident last night.

**Comment by gkasdorf** [comment] 2023-07-12 03:45
Upon more inspection, this looks at this point like a part of the Lemmy.world issues. Some of the UI issues should be fixed now though, and it should allow you to re-enable even if the JWT has expired that the server has.

But yea, we need to wait for Lemmy.world to resolve their issues. I won't close this until that happens so we can verify it is fixed.

**Comment by gkasdorf** [comment] 2023-07-13 07:52
I think these things are fixed. If anyone continues to have issues feel free to comment and I will re-open.

**Closed by gkasdorf** 2023-07-13 07:52 UTC
Labels: bug, on hold, high priority

**Comment by gkasdorf** [comment] 2023-07-13 10:11
Hmm I have an account there so let me do a test myself. Give me a few to get back to a computer. GavinSent from my iPhoneOn Jul 13, 2023, at 1:30 AM, fmflurry ***@***.***> wrote:﻿
I just tested with my account on programming.dev and it still returns a 401.
The problem is on programming.dev’s lemmy’s instance ?

**Comment by fmflurry** [comment] 2023-07-13 12:50
My lemmy.world account has notifications enabled but I don’t receive any notifications whereas my inbox show notifications when I start the app.

not the initial issue of this ticket but related to notifications
