### ISSUE TITLE
Multi Communities

### ISSUE THREAD

**Issue by bviefhues** [Memmy-App/memmy#528] opened 2023-07-09 11:51 UTC
**Describe the solution you'd like**
Support multi communities (or community groups). Offer a user interface for configuring a number of communities under a common name/label. That name would be app/device local only. 

In the Traverse tab, show multi communities in an iwn section and treat them like any community, i.e. offer to view, but with posts from all included communities. 

**Additional context**
This feature would be great to aggregate similar communities across instances. 

For additional insight: Apollo had this feature.

**Comment by ebits21** [comment] 2023-07-09 12:31
Duplicate of #293

**Closed** 2023-07-09 23:13 UTC
