### ISSUE TITLE
Ability to hide username in top bar

### ISSUE THREAD

**Issue by anxiolyt** [Memmy-App/memmy#667] opened 2023-07-14 21:01 UTC
I‘d like to be able to hide my username in the top bar.

My username has been removed in the screenshot.

![image](https://github.com/Memmy-App/memmy/assets/3084791/79640f6f-bb65-43e0-aae2-d31b1cbb51c1)

**Comment by eoddc5** [comment] 2023-07-14 21:08
closed as duplicate of closed issue #657

**Closed by eoddc5** 2023-07-14 21:08 UTC
Labels: enhancement
