### ISSUE TITLE
[MEM-104] Comments can’t include apostrophe

### ISSUE THREAD

**Issue by guillochon** [Memmy-App/memmy#377] opened 2023-07-03 22:54 UTC
**Describe the bug**
I get an illegal token error when I try to comment where the comment includes an apostrophe (e.g. “don’t”)

**To Reproduce**
1. Comment on a post
2. Type a word with an apostrophe in it
3. Try to submit

**Smartphone (please complete the following information):**
 - Device: iPhone XS
 - OS: Latest iOS

<sub>[MEM-104](https://linear.app/memmyios/issue/MEM-104/comments-cant-include-apostrophe)</sub>

**Comment by gkasdorf** [comment] 2023-07-03 23:02
That’s weird. Let me check but I don’t think I’ve seen that one…might need to escape the character or encode it for Lemmy to cooperate. Thanks for the report. GavinSent from my iPhoneOn Jul 3, 2023, at 3:55 PM, James Guillochon ***@***.***> wrote:﻿
Describe the bug
I get an illegal token error when I try to comment where the comment includes an apostrophe (e.g. “don’t”)
To Reproduce
Steps to reproduce the behavior:

Comment on a post
Type a word with an apostrophe in it
Try to submit

Smartphone (please complete the following information):

Device: iPhone XS
OS: Latest iOS

**Comment by gkasdorf** [comment] 2023-07-05 10:29
I am not able to reproduce this. I'm going to close it for now, but if you have other information to provide feel free to open a new ticket. Are you by any chance using a different language keyboard?

**Closed by gkasdorf** 2023-07-05 10:29 UTC
Labels: bug, linear
