### ISSUE TITLE
language_not_allowed When posting/replying on feddit.de

### ISSUE THREAD

**Issue by chrismarquardt** [Memmy-App/memmy#306] opened 2023-07-02 06:26 UTC
**Describe the bug**
When trying to reply on some feddit.de posts, memmy throws language_not_allowed

**To Reproduce**
1. Reply to comments
2. Example comment where this happens (updated the link): https://feddit.de/post/1218731

**Screenshots**
![IMG_3668](https://github.com/gkasdorf/memmy/assets/2527608/80d18edf-8e2b-4a88-b079-8fc9f8f1e54a)

**Smartphone (please complete the following information):**
 - Device: iPhone 13 Pro
 - OS: iOS 16.5.1

**Logs:**
Let me know if logs help and I’ll send them

**Comment by gkasdorf** [comment] 2023-07-02 06:33
This issue keeps mystifying me. I'll look into it again. I purposefully set the language ID to be the same ID as the one of the comment or post you are replying from to avoid it, so not sure what's going on. Thanks.

**Comment by gkasdorf** [comment] 2023-07-02 06:34
Wow, I see the issue...sigh

I'll fix it now and have it up tonight.

**Comment by gkasdorf** [comment] 2023-07-02 06:55
Ok fixed. Hate Javascript sometimes...

**Comment by chrismarquardt** [comment] 2023-07-02 12:32
Not sure it’s fixed. Tried to comment on this post and i keep getting the same language error 

The post in question:
https://feddit.de/post/1242900

**Comment by gkasdorf** [comment] 2023-07-02 22:30
> Not sure it’s fixed. Tried to comment on this post and i keep getting the same language error
> 
> The post in question: [feddit.de/post/1242900](https://feddit.de/post/1242900)

So I'm having a ridiculous time trying to reproduce this. I know what caused the issue yesterday but now I can't seem to repro at all. Let me show you what I am seeing:

1. You reply to a comment. We don't know what the language ID is supposed to be, so we check the ID of either the post/comment you're replying to or one of the posts in the community
2. We use that same ID to submit the new comment. This logic makes sense because if someone else commented with that language ID, then it should be valid.

This is what I get whenever I'm replying to different comments/posts with varying options:

```
 LOG  0
 LOG  37
 LOG  0
 LOG  37
 LOG  37
```

The zeros indicate that it's using the default option (there wasn't one set) and the 37 indicates that it was English.

I wonder if maybe the zero is messing it up and I should just not be sending anything. Let me try replying to that post you just linked there and see what happens...

**Comment by gkasdorf** [comment] 2023-07-02 22:37
@adude007 @chrismarquardt 

So if I try to reply to something on feddit.de, my language ID gets set to 32
```
 LOG  32
```

I'm super confused why this wouldn't let you submit the comment. I've tested replying to both the post to a comment (didn't test post yet but it's the same logic so it should work the same and your issues appear to be with comments).

I also just made a comment on a feddit.de post that seemed to go through just fine (language ID was 32).

Can you tell me if this happens on ALL feddit posts?

@adude007 I don't know what specific post you were having issues with but I am assuming that it's on a non-english community?

**Comment by chrismarquardt** [comment] 2023-07-02 23:47
Not on all posts. I can replied to one of my own without issues and without the need to make any language selection. This one:
https://feddit.de/post/1163873

I’ve just tried to comment on this one, 
https://feddit.de/post/1218731
using the web interface, and not selecting a language from the pulldown, and it wouldn’t go through, showing an infinite spinner. Only when deliberately selecting a language, would it go through.

my profile has Undetermined, Deutsch, English set as my languages in case that might matter

**Comment by gkasdorf** [comment] 2023-07-02 23:57
@chrismarquardt I don't *think* you have a default option selected should matter, but let me make sure by running a test.

Frankly, the whole idea is pretty confusing. Since you can select any language you want when you make a post, there's zero point in Lemmy asking about a language ID at all. In fact, it's best probably if communities just don't set a language requirement because of these issues, as well as issues with Kbin (there's a whole different issue when it comes to Kbin and languages...)

I'll keep digging though. I couldn't find that post you inked up there, hopefully I can find it this time.

**Comment by adude007** [comment] 2023-07-03 00:09
> @adude007 @chrismarquardt
> 
> So if I try to reply to something on feddit.de, my language ID gets set to 32
> 
> ```
>  LOG  32
> ```
> 
> I'm super confused why this wouldn't let you submit the comment. I've tested replying to both the post to a comment (didn't test post yet but it's the same logic so it should work the same and your issues appear to be with comments).
> 
> I also just made a comment on a feddit.de post that seemed to go through just fine (language ID was 32).
> 
> Can you tell me if this happens on ALL feddit posts?
> 
> @adude007 I don't know what specific post you were having issues with but I am assuming that it's on a non-english community?

@gkasdorf , no it was on a technology@lemmy.world post. It hasn’t happened to me since.

**Comment by chrismarquardt** [comment] 2023-07-03 00:14
Here’s another one that took my comment just fine https://feddit.de/post/1208142

**Comment by adude007** [comment] 2023-07-03 12:57
![IMG_0952](https://github.com/Memmy-App/memmy/assets/73857010/7265807c-d884-405c-a7d2-ef7d3ab2c162)

I was able to comment on this austria@feddit.de post this am. On 0.0.2.9

**Comment by gkasdorf** [comment] 2023-07-04 07:32
I'd really like to fix this but it's super weird. I'm hearing that it actually happens in other apps too, not just Memmy. Wefwef and Mlem seem to have the same issue...

**Comment by chrismarquardt** [comment] 2023-07-04 08:00
As this (or something related to it) seems to also happen when using the web interface (I still can’t post to feddit.de/c/fotografie without explicitly choosing the language), it might be related to the server or to the configuration of a specific community.

**Comment by gkasdorf** [comment] 2023-07-04 08:01
@chrismarquardt if you select the language does it work? That's probably the thing I am most confused about is that I am trying to set a language. I wonder if the requirements for a post are different than a comment and that's where I'm going wrong...I'll do some debugging on that tomorrow. Thanks for letting me know about that.

**Comment by chrismarquardt** [comment] 2023-07-05 08:52
I looked at the debug log, but that won't help you. Right now it only shows
[1688552057780] Error submitting post.
[1688552057780] language_not_allowed
[1688552072761] Ending refresh interval.
[1688552078363] Starting refresh interval.

Could you temporarily instrument the next version with more debugging info around posting/commenting? I could then force the error(s) and send you the logs.

**Comment by gkasdorf** [comment] 2023-07-05 10:55
I added a little more there so we can see if the language Id is getting properly set 👍

**Comment by chrismarquardt** [comment] 2023-07-05 20:17
Debug log when trying to create a post in feddit.de/c/fotografie (also sent via email)

[1688595172684] Error submitting post.
[1688595172685] language_not_allowed
[1688595172685] Language ID: 0
[1688595172685] Community ID: 45137

**Comment by bviefhues** [comment] 2023-07-06 05:23
Same error here, version 0.0.2 (17). 

![image](https://github.com/Memmy-App/memmy/assets/1117300/b3559e8b-0ac4-487d-9eea-594876eeafc4)

**Comment by gkasdorf** [comment] 2023-07-06 05:24
> Same error here, version 0.0.2 (17).
> 
> ![image](https://user-images.githubusercontent.com/1117300/251352062-b3559e8b-0ac4-487d-9eea-594876eeafc4.png)

Do you have a default language set on your Lemmy account?

**Comment by bviefhues** [comment] 2023-07-06 05:53
> > Same error here, version 0.0.2 (17).
> 
> > 
> 
> > ![image](https://user-images.githubusercontent.com/1117300/251352062-b3559e8b-0ac4-487d-9eea-594876eeafc4.png)
> 
> 
> 
> Do you have a default language set on your Lemmy account?

This is how language is set on the account:

![image](https://github.com/Memmy-App/memmy/assets/1117300/ec59670b-f4b9-4b3c-a97e-c6618e9b152e)

**Comment by gkasdorf** [comment] 2023-07-06 10:47
@chrismarquardt See, this is the super weird thing. If we go and check a post from that community, they are posted with the language ID of zero. Meaning...we should think that posts with the language zero are allowed in that community.

I am speculating here, but I think that perhaps Lemmy does not honor the language ID you set when submitting the post and might instead use one of your selected languages. Can you try removing your default languages on the website and seeing if that helps at all? (If you already don't then I am really stumped on this one...)

@bviefhues Can you try to do the same thing and remove your preferred/default languages and try again?

The whole thing is pretty weird and pointless, in my opinion. I can see it being useful for filtering out content that you might not want to see based on language, but the fact that anyone can select any language they want anyway makes me wonder why it's even a feature in Lemmy. Regardless, I think it might be some sort of bug on their end (I've heard this happens in WefWef and Mlem as well...)

**Comment by bviefhues** [comment] 2023-07-06 10:55
> @chrismarquardt See, this is the super weird thing. If we go and check a post from that community, they are posted with the language ID of zero. Meaning...we should think that posts with the language zero are allowed in that community.
> 
> 
> 
> I am speculating here, but I think that perhaps Lemmy does not honor the language ID you set when submitting the post and might instead use one of your selected languages. Can you try removing your default languages on the website and seeing if that helps at all? (If you already don't then I am really stumped on this one...)
> 
> 
> 
> @bviefhues Can you try to do the same thing and remove your preferred/default languages and try again?
> 
> 
> 
> The whole thing is pretty weird and pointless, in my opinion. I can see it being useful for filtering out content that you might not want to see based on language, but the fact that anyone can select any language they want anyway makes me wonder why it's even a feature in Lemmy. Regardless, I think it might be some sort of bug on their end (I've heard this happens in WefWef and Mlem as well...)


@gkasdorf I unselected the three language items and saved the profile on the Lemmy web instance. 

Then tried commenting on the same post. 

Same error.

**Comment by gkasdorf** [comment] 2023-07-06 10:56
@bviefhues What instance and community? Let me try to repro right now.

**Comment by gkasdorf** [comment] 2023-07-06 11:06
Hmm, you are both on Feddit, and I think I've heard of someone else having a similar issue.

I'm going to create an account there and see if they approve it (I'll mention it's for testing out some issues for their users).

But I'm going to try something else right now too. I just went and enabled Deutsch in the community memmy@lemmy.ml. Can you try to post/comment there now?

**Comment by bviefhues** [comment] 2023-07-06 11:19
@gkasdorf Just tried again. Same error.

**Comment by gkasdorf** [comment] 2023-07-06 11:23
@bviefhues Do you know if any of the admins over at your instance have a Matrix or something that I could talk to them on?

**Comment by chrismarquardt** [comment] 2023-07-06 19:53
Matrix and mods in screenshot below. Thanks for putting your time into this, so much appreciated!!

![IMG_3746](https://github.com/Memmy-App/memmy/assets/2527608/58ec1a9e-d7d1-4d30-ab2b-e1ac1fb944cf)

**Comment by adude007** [comment] 2023-07-08 14:32
Had the error come up again. 0.1.0.11. 

I was trying to post a comment here: https://kbin.social/m/aww@lemmy.world/t/158311  
![IMG_0988](https://github.com/Memmy-App/memmy/assets/73857010/9402f3c2-8766-428e-a85c-2699939a7f4d)

**Comment by gkasdorf** [comment] 2023-07-12 03:41
@eoddc5 I really hope this is something that gets worked out over with Lemmy. There's a bunch of super weird edge cases that just don't make any sense.

There are multiple issues over in their tracker: https://github.com/LemmyNet/lemmy/issues/3451 https://github.com/LemmyNet/lemmy/issues/3150

**Comment by kevinboss** [comment] 2023-07-14 15:35
> is anyone still experiencing this? I haven’t seen it in a few days

Just had it when trying to comment in dach on feddit.de. Using Beta 1 of 0.3.
![IMG_1433](https://github.com/Memmy-App/memmy/assets/4927587/9587c1de-4c12-44d6-b1b8-aaf3adae4a71)

**Comment by Nutomic** [comment] 2023-07-19 10:15
Lemmy maintainer here. Does memmy automatically pass a `language_id` when calling create comment? The problem can likely be fixed by leaving that field empty/null. Then the backend will automatically set a language.

**Comment by gkasdorf** [comment] 2023-07-20 01:06
> Lemmy maintainer here. Does memmy automatically pass a `language_id` when calling create comment? The problem can likely be fixed by leaving that field empty/null. Then the backend will automatically set a language.

I'll play around with this later. It might be that it's sending `0` since that is the language that was used previously (which would make sense that it would send zero). I'll do something to just leave it undefined if the API tells us the language is `0`. Thanks!

**Comment by Haui1112** [comment] 2023-07-21 07:02
Hello,
I‘ve also encountered this. First other communities and comments, now in a community I made on firefox (ubuntuserver@tchncs.de) which I‘m trying to fill with content but it wont let me.

keeps repeating „you‘re not allowed to post in this language“ (my language is english, tchncs supports english, the community is in english I dont know what to do.

i also dont know how to change the language settings in memmy so I could play around with it?

have a good one.

**Comment by gkasdorf** [comment] 2023-07-21 11:37
I think I may have found a solution, we will see in the next release.

**Comment by Haui1112** [comment] 2023-07-21 12:33
> I think I may have found a solution, we will see in the next release.

Thank you very much! Looking forward to it! :)

**Comment by gkasdorf** [comment] 2023-10-21 04:57
New language selection system should fix all of these issues.

**Closed by gkasdorf** 2023-10-21 04:57 UTC
Labels: bug, question, on hold
