### ISSUE TITLE
Add list of filtered communities to filtered section of settings

### ISSUE THREAD

**Issue by tranquilcarbon** [Memmy-App/memmy#986] opened 2023-08-13 04:41 UTC
### Check for open issues

- [X] I have verified that another issue for this is not open, or it has been closed and has not been properly implemented.

### What is the feature that you would like to have added?

Currently, once a community is filtered and the post is unloaded, there is no way to unfiltered it to my knowledge. 

### Solution

I would like to propose that a new list be added to the filters section in settings which will show you all the community’s that are filtered and allow for removal and addition of communities.

### Alternatives

I don’t believe there are any alternative solutions, but I am open to suggestions.

**Comment by sgriff96** [comment] 2023-08-13 18:43
Dupe of #675

**Closed** 2023-08-13 18:43 UTC
Labels: medium priority, feature request
