### ISSUE TITLE
See community stats in search results

### ISSUE THREAD

**Issue by Bcrabbers** [Memmy-App/memmy#626] opened 2023-07-12 17:25 UTC
When searching for communities, it would be helpful to see stats like subscriber or post count, etc in the results next to the community name.

Since there can be multiple, duplicate communities across instances, quickly seeing which is the most popular vs which ones are dead would be great.

(Also, can we set a default search mode so we can just hit “search” on the keyboard rather than specifically tapping “communities” or whatever? Currently that button doesn’t do anything)

**Comment by eoddc5** [comment] 2023-07-12 17:50
closing: duplicate of #338

**Closed** 2023-07-12 17:51 UTC
Labels: duplicate, enhancement, low priority, visual
