### ISSUE TITLE
[Bug] App not respecting system theme

### ISSUE THREAD

**Issue by SpenHub** [Memmy-App/memmy#898] opened 2023-07-30 16:57 UTC
### Check for open issues

- [ ] I have verified that another issue for this is not open, or it has been closed and has not been fixed.

### Minimal reproducible example

As of a few weeks ago the app is no longer respecting system themes. 

### Expected Behavior

When I’m using light mode, the app should detect and present a light theme.

When I’m using dark mode, the app should detect and present a dark theme. 

### Version

0.5.0.13

### App Store or TestFlight?

App Store

### iOS Version

16.x

### Device

iPhone 13 mini

**Comment by eoddc5** [comment] 2023-07-30 17:10
duplicate of #896 from an hour or two ago

**Closed by eoddc5** 2023-07-30 17:10 UTC
Labels: bug, triage
