### ISSUE TITLE
Subscriber count always shows 3k when searching

### ISSUE THREAD

**Issue by seaneoo** [Memmy-App/memmy#769] opened 2023-07-19 18:40 UTC
**Describe the bug**
When searching for a community, the subscriber count is always  listed at 3,000 (displayed as 3k). This occurred every time I searched a community.

**To Reproduce**
1. Go to to the "Search" tab
2. Enter your search query or community name.
3. Click "Search Communities"

**Expected behavior**
This number should be the proper (or close to) subscriber count of the individual community. 

**Screenshots**
![image](https://github.com/Memmy-App/memmy/assets/15949898/2a3d5469-2711-410e-bf36-e392b7f16fa6)

![image](https://github.com/Memmy-App/memmy/assets/15949898/c03c8f45-e699-41dd-a445-fafcf2daeee9)

**Smartphone (please complete the following information):**
 - Device: iPhone 12
 - OS: iOS 16.5.1 (c)
 - Version: 0.4 (2)

**Comment by seaneoo** [comment] 2023-07-19 18:44
This also occurs when you click on the community from the search results. The incorrect count is displayed in the info.

**Comment by eoddc5** [comment] 2023-07-19 19:36
Duplicate of #756 which is being fixed

**Closed as not planned by eoddc5** 2023-07-19 19:36 UTC
Labels: duplicate, wontfix
