### ISSUE TITLE
[Bug]: Search bar halfway off the screen

### ISSUE THREAD

**Issue by ProvokedGamer** [Memmy-App/memmy#993] opened 2023-08-14 23:14 UTC
### Check for open issues

- [X] I have verified that another issue for this is not open, or it has been closed and has not been fixed.

### Minimal reproducible example

When I open up Memmy and go to the search tab, 50% of the time the search bar is halfway off the screen. When I try to tap on the search bar in that state, it doesn’t bring up the keyboard (the app doesn’t do anything).

![2673F880-B70B-46A9-B57F-B13FC0AF8F4F](https://github.com/Memmy-App/memmy/assets/119907145/4c227e8c-69ca-404f-87ab-57306e3dd1cc)

Reproducible Steps:

1. Open up Memmy
2. Go to the search tab
3. If the bug doesn’t appear, kill Memmy in the app switcher and try again

### Expected Behavior

When I go to the search tab, the search bar should be in the centre, and clicking on the search bar should bring up the keyboard so that I can search.

### Version

0.6.1 (1)

### App Store or TestFlight?

TestFlight

### iOS Version

15.x

### Device

iPhone 8+

**Comment by eoddc5** [comment] 2023-08-14 23:17
this might be an iPhone 8 issue....ive not seen this in any build yet on my 14

@sgriff96 or @gkasdorf ?

**Comment by sgriff96** [comment] 2023-08-14 23:20
Yea i can't reproduce this on an 11 pro. Does this happen very consistently to you? @ProvokedGamer

**Comment by ProvokedGamer** [comment] 2023-08-14 23:22
Yeah. It happens about 50-70% of the time I open Memmy.

**Comment by ProvokedGamer** [comment] 2023-08-14 23:33
> I think we're gonna remove the search bar from the header there anyways which would probably fix this from happening

Oh ok, great!

@sgriff96

**Comment by ibennetch** [comment] 2023-09-03 14:59
For what it’s worth, this happens almost all the time for me on an iPhone SE (2020). I remember only one time I was able to use the search properly. 

I see you said you plan to move the search bar which is fine, but just wanted to give another data point about this.

**Comment by gkasdorf** [comment] 2023-10-21 04:58
This is fixed now.

**Closed by gkasdorf** 2023-10-21 04:58 UTC
Labels: bug, medium priority

**Comment by ProvokedGamer** [comment] 2023-10-21 16:39
> This is fixed now.

Thanks!!!
