### ISSUE TITLE
Add alphabetized selection feature to traverse

### ISSUE THREAD

**Issue by eoddc5** [Memmy-App/memmy#531] opened 2023-07-09 16:43 UTC
Alphabetic menu in traverse tab would be awesome

Native iOS and lots of apps use this to help sort large alphabetized lists. You can click the S and drops you down. Click B and you’re back at B.

**Comment by eoddc5** [comment] 2023-07-09 17:19
![Uploading IMG_6916.jpeg…]()

**Comment by bviefhues** [comment] 2023-07-09 18:25
Duplicate of #290

**Closed** 2023-07-09 23:10 UTC
Labels: enhancement
