### ISSUE TITLE
Comment Jump Button

### ISSUE THREAD

**Issue by QuarterSwede** [Memmy-App/memmy#488] opened 2023-07-08 12:49 UTC
Would love to see a comment jump button added to _jump to the next parent comment_ in a post. Haven’t seen any other Lemmy/kbin app do that yet. Lemmy has grown big enough that it’s needed in certain communities.

**Comment by gkasdorf** [comment] 2023-07-08 12:52
I think I’m going to play with this later today :)GavinSent from my iPhoneOn Jul 8, 2023, at 5:50 AM, QuarterSwede ***@***.***> wrote:﻿
Would love to see a comment jump button added to jump to the next parent comment in a post. Haven’t seen any other Lemmy/kbin app do that yet. Lemmy has grown big enough that it’s needed in certain communities.

**Comment by QuarterSwede** [comment] 2023-07-08 12:54
Oh, you’re a saint 👼.

**Comment by sgriff96** [comment] 2023-07-08 21:05
Dupe of #284

**Closed by sgriff96** 2023-07-08 21:05 UTC
Labels: enhancement
