### ISSUE TITLE
Comment bug

### ISSUE THREAD

**Issue by shofhna** [Memmy-App/memmy#813] opened 2023-07-22 12:44 UTC
### Check for open issues

- [X] I have verified that another issue for this is not open, or it has been closed and has not been fixed.

### Minimal reproducible example

Try to add comment then deleted
Go to feed screen > sort listing> top> month
You will see your deleted comment in every post for 1 secound then disappear

See the full video 

https://drive.google.com/file/d/1KYQtNmTRw_pQaJ7cm3zfy2XnUUg4kq05/view

### Expected Behavior

Deleted comment not showen in all post

### Version

0.5(4)

### App Store or TestFlight?

TestFlight

### iOS Version

16.x

### Device

Iphone 11 pro

**Comment by pitrisss** [comment] 2023-07-22 12:53
I can recreate the issue. I have not deleted the comment. I have posted a comment on one post, and then it is visible on second post.

https://github.com/Memmy-App/memmy/assets/19386789/c0db8b70-5229-4f08-80f7-239e33d0cc8e

**Comment by ebits21** [comment] 2023-07-22 13:31
Likely related to #788

**Comment by sgriff96** [comment] 2023-07-22 20:02
Closing as dupe of #788

**Closed by sgriff96** 2023-07-22 20:02 UTC
Labels: bug, low priority
