### ISSUE TITLE
Scroll to next root comment button

### ISSUE THREAD

**Issue by ericschmar** [Memmy-App/memmy#284] opened 2023-07-01 13:23 UTC
**Is your feature request related to a problem? Please describe.**
When viewing a post in Memmy, I find it difficult to find the next root comment. Despite the color coding, a solution like Apollo's with a FAB button that takes you to the next root comment would be awesome. 

**Describe alternatives you've considered**
There could always be improvements on the hierarchy view of comments, be it disabling profile pictures, font scaling, color, etc. that could help reading comprehension for these levels of comments. 

**Additional context**
Apollo is closed now, so I can't post a screen shot. But the FAB but I'm referring to was the blue bottom that sat in the bottom right corner on top of everything and didn't move with scrolling. When tapped, it would scroll you to the next root comment.

**Comment by sgriff96** [comment] 2023-07-08 21:07
Dupe of #111

**Closed by sgriff96** 2023-07-08 21:07 UTC
Labels: enhancement, linear
