### ISSUE TITLE
Search in community

### ISSUE THREAD

**Issue by chrismarquardt** [Memmy-App/memmy#494] opened 2023-07-08 15:54 UTC
**Is your feature request related to a problem? Please describe.**
When a community is open I’d love to have a way to search only in that community

**Describe the solution you'd like**
On swipe down reveal a search bar at the top like many Apple apps do it.

**Comment by sgriff96** [comment] 2023-07-08 21:00
Dupe of #294

**Closed by sgriff96** 2023-07-08 21:00 UTC
Labels: duplicate, enhancement
